name = "PositiveFactorizations"
uuid = "85a6dd25-e78a-55b7-8502-1745935b8125"
author = ["Tim Holy <tim.holy@gmail.com"]
version = "0.2.4"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[compat]
julia = "0.7, 1"

[targets]
test = ["Test", "ForwardDiff", "ReverseDiff"]
